### ISSUE TITLE
BUG: Scrolling through an embedded drawing in mobile opens the drawing in Excalidraw

### ISSUE THREAD

**Issue by danisty** [zsviczian/obsidian-excalidraw-plugin#1003]
**Your environment**
```
SYSTEM INFO:
	Operating system: android 12 (Xiaomi M2003J15SC)
	Obsidian version: 1.4.1 (83)
	API version: v1.0.3
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Aura
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 10
		1: LanguageTool Integration v0.3.3
		2: Highlightr v1.2.2
		3: Style Settings v1.0.0
		4: Tasks v1.24.0
		5: Outliner v4.2.1
		6: Editor Syntax Highlight v0.1.3
		7: Advanced Tables v0.18.1
		8: Dataview v0.5.55
		9: Quick Latex for Obsidian v2.5.1
		10: Excalidraw v1.8.12
```

**Describe the bug**
Embedding a Excalidraw drawing into a note, then trying to scroll through the note in mobile, if you accidentally hover over the drawing while scrolling, the drawing will open in Excalidraw in a new/current tab.

**To Reproduce**
1. Embed a Excalidraw drawing into a note
2. Scroll through the note on mobile by tapping on the drawing then moving down/up

**Expected behavior**
Don't open the drawing.

**Video**
https://streamable.com/bza88a

**Comment by zsviczian** [comment]
I am able to reproduce.

**Comment by zsviczian** [comment]
Fixed in 1.8.13 - will release it in a couple of days once some other fixes are in.

**Comment by tim-forrer** [comment]
Hi thanks for working on this - I've run into what I think is the same issue on v1.8.26.
It is not 100% reproducible but still happens as seen in this clip
https://streamable.com/xx1db6

```
SYSTEM INFO:
	Operating system: android 13 (samsung SM-G988B)
	Obsidian version: 1.4.3 (95)
	API version: v1.1.16
	Login status: not logged in
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 4
		1: Style Settings v1.0.3
		2: Minimal Theme Settings v6.3.1
		3: Excalidraw v1.8.26
		4: Settings Search v1.3.7
```

**Comment by DeltaMod** [comment]
Hello,
This issue is still happening. All I'm trying to do is scroll through the image to the next one, instead the file opens in edit mode. 

```
System info::
Operating system: android 14 (samsung SM-X510)
	Obsidian version: 1.7.7 (171)
	API version: v1.7.7
	Login status: not logged in
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 1
                 -Excalidraw 2.7.5

```
https://files.catbox.moe/ff4yqi.mp4

I've searched far and wide for a solution where "two finger gestures" cannot be used to open embed images in edit mode, and have found nothing.

**Comment by zsviczian** [comment]
@DeltaMod, This is a closed issue, your issue will get lost here. I don't look at closed issues. Please open a new issue, reference this old issue and I'll take a look. I don't promise a fast response though, but at least the issue will not get lost.
