### ISSUE TITLE
Bug: Embedding a markdown file defaults to a transparent background ignoring the current selected element background color

### ISSUE THREAD

**Issue by postkevone** [zsviczian/obsidian-excalidraw-plugin#2172]
### Have you searched for existing issues (including closed ones)?

- [x] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [x] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Darwin Kernel Version 23.6.0: Thu Sep 12 23:34:49 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_X86_64 23.6.0
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 7
		1: Excalidraw v2.7.1
		2: Folder notes v1.7.32
		3: Trash Explorer v1.2.3
		4: Settings Search v1.3.10
		5: Find orphaned files and broken links v1.10.1
		6: Automatic Table Of Contents v1.5.0
		7: Open In New Tab v1.0.9

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

When embedding a markdown file from the Obsidian vault, the element background defaults to transparent, even if the "Match Element Background Color" setting from "Embeddable Element Settings" is set to ON.

### Steps to reproduce

1. Import a markdown note with "Insert ANY file".
2. Import as "as Embeddable".
3. The imported note's background is transparent (current element background color is ignored).

### Expected behavior

The embedded markdown note's background should reflect the currently selected element background.

**Comment by zsviczian** [comment]
this is likely due to your default embed settings:

![image](https://github.com/user-attachments/assets/0efc827c-76d5-4595-a84d-949bd427814b)

**Comment by postkevone** [comment]
I may be misunderstanding the purpose of the "Match Element Background Color" setting.
Isn't it supposed to use the background color currently selected for other elements, such as rectangles and diamonds?

These are my settings:

![image](https://github.com/user-attachments/assets/ef9e2956-ff30-4b60-8353-c1d8cf05e5f3)

**Comment by zsviczian** [comment]
ah... I see, indeed the element is created with a transparent color instead of honoring the active element background color. That is indeed a bug.

if you manually set the background color of the element after embedding the embeddable, it does actually work, so the issue is not with your embeddable settings.

**Comment by zsviczian** [comment]
Interestingly, I explicitly set the background and stroke color to transparent when adding a new embeddable. I've now tied this to embeddable default settings.

Fixed in 2.7.2

**Comment by postkevone** [comment]
Thanks for the quick fix!
The "Import ANY file" button now respects the element background color.

However, I noticed that the problem persists when using the ea.addEmbeddable() method to import a file. Is this correlated?

**Comment by zsviczian** [comment]
ea will always add elements following the ea.style settings

https://zsviczian.github.io/obsidian-excalidraw-plugin/API/introduction.html#basic-logic-of-using-excalidraw-automate
