### ISSUE TITLE
Opening link from Excalidraw also opens web browser tab with "about:blank"

### ISSUE THREAD

**Issue by ultron** [zsviczian/obsidian-excalidraw-plugin#420]
**Describe the bug**
Clicking on the link icon from an Excalidraw drawing opens the corresponding Obsidian document, but then goes on to open a web browser with the "about:blank" 

**To Reproduce**
1. Create empty Excalidraw drawing. Include a link to an Obsidian file
2. Click on the link to open
3. Browser displays about:blank

**Expected behavior**
Browser does not open for Obsidian links.

**Screenshots**
See attached
![excalidraw-open-link](https://user-images.githubusercontent.com/605820/153308438-3f3b06ef-5eb5-40e3-bf84-aad4ab245280.png)
![about-blank-in-browser](https://user-images.githubusercontent.com/605820/153308478-7e8fc50b-61b0-4dbd-9112-4a84fc4c5f79.png)

**Desktop (please complete the following information):**
 - OS: popos 21.10 (Linux) 
 - Browser Brave [Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)]
 - Obsidian 0.13.23, Excalidraw 1.6.5

**Additional context**
This could be Linux specific. 
I tested the same document/vault on Windows and couldn't reproduce, but is 100% reproducible on Linux.
Any tips on how to eliminate the browser being invoked?

**Comment by zsviczian** [comment]
It's not just a Linux thing. I implemented an onLinkOpen function in Excalidraw ahead of the Excalidraw team. When I merged the official soluion I did not spot this difference in code. I will resolve this tonight.

**Comment by zsviczian** [comment]
I pushed a fix just now.

**Comment by ultron** [comment]
Wow, so fast. Confirmed working. Thanks. You rock.

**Comment by sdzialowski-godaddy** [comment]
Issue is back, I've tried on Chrome and Brave, the same, redirects to about:blank.
I'm currently on mac:
```
Model Name:	MacBook Pro
Model Identifier:	MacBookPro18,1

chrome:
    Version 122.0.6261.112 (Official Build) (arm64)

brave:
    [Version 1.64.116 Chromium: 123.0.6312.105](https://brave.com/latest/)

I'm testing it using regular public: https://excalidraw.com/
```

**Comment by zsviczian** [comment]
I do not manage excalidraw.com ; It is fully independent from the Obsidian Plugin. Links in Obsidian work. However, I've also noticed the problem on excalidraw.com and opened an issue few days ago:  https://github.com/excalidraw/excalidraw/issues/7858

**Comment by sdzialowski-godaddy** [comment]
Yea indeed, Wrong issue tracker. I apologize. I've reported it now in right place: https://github.com/excalidraw/excalidraw/issues/7866
