### ISSUE TITLE
Reverted images are not exported reverted

### ISSUE THREAD

**Issue by AMGMNPLK** [zsviczian/obsidian-excalidraw-plugin#811]
If you resize an image in order you change its orientation (up-down or left-right) and you export the excalidraw as png you will find the imagen on its original orientation

**Screenshots**
![image](https://user-images.githubusercontent.com/19272675/190905116-675fad7e-9851-41c9-bf9a-052a1adc9c0d.png)

**Environment:**
 - Windows 10
 - Plugin version: 1.7.19
 - Obsidian version: v0.15.9

**Comment by zsviczian** [comment]
yes. this is a known issue. I have seen some very recent development on excalidraw.com that might solve this issue. Will deploy the excalidraw.com changes to Obsidian soon. 
https://github.com/excalidraw/excalidraw/pull/5700

**Comment by zsviczian** [comment]
Fixed in 1.7.21 - will releaese today

**Comment by AMGMNPLK** [comment]
We still have a problem with resizing (changing proportions) and with tranparency in the case of the embedded excalidraw inside other excalidraw.

**Comment by zsviczian** [comment]
Transparency you can solve at the file level by adding front matter keys to the image or at a holistic level for your entire vault in plugin settings:

```markdown
---
excalidraw-plugin: parsed
excalidraw-export-transparent: true
excalidraw-export-dark: true
excalidraw-export-padding: 5
---
```

Based on my testing resizing works correctly, but changing proportions does not (I wasn't aware of this).

**Comment by AMGMNPLK** [comment]
The transparency trick doesn't work for a collage where you have a fully opaque image and a partially transparent one, does it? Or how?
