### ISSUE TITLE
Enable or add the option to enable pinch-to-zoom while using freedraw tool in pen lock mode.

### ISSUE THREAD

**Issue by JokerXiL** [zsviczian/obsidian-excalidraw-plugin#828]
Not sure why this is universally disabled in the first place. I am using obsidian on iPad pro with apple pencil, I have rolled back to version 1.5.23 to test the freedraw tool when pinch-to-zoom is still enabled, there are no problems at all, problems such as #325 do not occur for me. So I think disabling a feature to fix a problem that does not occur for all people is not a good move at all.

**Comment by zsviczian** [comment]
making this an option is a good idea.

**Comment by carlstedt1** [comment]
Any update on making this possible?

I have little coding experience and thought it would be easy to fix this in the javascript file. But could not find much regarding pinch to zoom.

**Comment by zsviczian** [comment]
This is not easy to fix from a javascript file, but not a big deal in the codebase. 
Frankly, I have forgotten about this request.
I implemented it just now. Once 1.8.11 is released you will need to change your Excalidraw template to include `"allowPinchZoom": true` in appState. Please take a look at the bottom of the example.

![image](https://user-images.githubusercontent.com/14358394/212986542-fc7a4de2-3a60-4d8f-8b7f-7abbeecd9e17.png)

**Comment by spaghetmaster** [comment]
Hey I tried adding `"allowPinchZoom": true` to the appState but it doesn't seem to work and it disappears after reentering md view

**Comment by JavaneseIvankov** [comment]
Just added "allowPinchZom": true into the decompressed excalidraw file, but i still can't pinch zoom. Is there any update for this issue?
